name: publish
on: push
jobs:
  publish-docker-image-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        run: |
          cd docker
          docker build . -t mrc4tt/miksen:latest
          docker push mrc4tt/miksen:latest
